export const jobsTemplates = [
  {
    id: "1",
    templateTitle: "Deep dive",
    templateDescription: null,
    title: "Deep dive",
    slug: "deep-dive",
    description:
      "<h2>Về công việc</h2><p><em>Viết ~2 đoạn văn giải thích công việc. Đoạn đầu tiên nên bao gồm bối cảnh và nền tảng có liên quan về dự án của bạn. Đoạn thứ hai nên giải thích mục tiêu của công việc (ví dụ: các lĩnh vực cần khám phá, các tính năng cần thảo luận, bối cảnh xung quanh mục đích của công việc, v.v.). Vui lòng đảm bảo viết công việc ở ngôi thứ 3 (tức là tránh &ldquo;chúng tôi&rdquo;). </em></p><p>&nbsp;</p><p>&nbsp;</p><h2>Tiêu chí đánh giá</h2><p><em>Người tìm việc sẽ sử dụng các gạch đầu dòng bên dưới để hiểu cách họ sẽ được đánh giá. Vui lòng thêm nhiều tiêu chí hơn (ví dụ: nếu bạn muốn họ thảo luận về một tính năng cụ thể trong dự án của bạn) hoặc chỉnh sửa các dấu đầu dòng bên dưới nếu cần.</em></p><p>&nbsp;</p><h3>Yêu cầu sâu hơn</h3><ul><li>Bạn đã khám phá nền tảng của dự án?</li><li>Does your essay talk about the key features of the project?</li><li>Is your essay the one-stop-resource for people to get up to speed with this project?</li><li>Bạn đã tìm hiểu mọi thứ cần biết về dự án chưa?</li><li>Did you take screenshots, provide a step by step guide to onboarding, and clearly articulate the value the project offers?</li><li>Did you join the project&rsquo;s Discord and get a feel for the community?</li><li>Bạn đã thử tham gia cuộc thi và giải thích những ưu/nhược điểm tương đối của dự án này chưa?</li></ul><p>&nbsp;</p><h3><strong>Phong cách viết</strong></h3><ul><li>Did you write a compelling introduction and a satisfying conclusion?</li><li>Bài viết của bạn có dễ đọc và thú vị không?</li><li>Bạn có tránh dùng những biệt ngữ quá phức tạp không?</li><li>Bạn có giải thích các khái niệm theo cách mà một người mới làm quen với tiền điện tử có thể hiểu được không?</li></ul><p>&nbsp;</p><h3><strong>Yêu cầu nộp đơn</strong></h3><ul><li>Did you write your essay in English?</li><li>Is your submission at least 1,000 words? Note that typical job winners are ~2,000 words.</li><li>Did you include links to your sources under the title &ldquo;References&rdquo;? If you have used external sources and no references are included, your job could be rejected on grounds of plagiarism.</li></ul><p>&nbsp;</p><h2>Tài liệu</h2><p><em>Please add any links to your project, socials, or any reference essays that may help the job hunters write a great deep dive. Consider including your Medium/Substack, Twitter, Discord, docs, website, and anything else that might prove helpful.</em></p><ul><li>Deep Dive Guidelines: https://superteamdao.notion.site/Deep-Dive-Job-Guidelines-bb86ec5ac3a14087b018b90afe69d5bd</li></ul><p>&nbsp;</p><h2>Điều khoản</h2><p>Việc tham gia vào công việc này là hoàn toàn tự nguyện. Công việc là một cách để học hỏi và tận dụng các cơ hội để xây dựng trên web3. Đây không phải là công việc toàn thời gian cũng như không phải là sự tham gia dựa trên dự án. Xin lưu ý rằng các công ty sẽ không có thời gian để đưa ra phản hồi riêng lẻ do số lượng bài đăng mà chúng tôi nhận được quá nhiều.</p>",
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#FDF8F0",
    emoji: "✍️",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    created_at: "2023-06-08T10:09:56.130Z",
    updated_at: "2023-06-08T10:09:56.130Z",
    skills: [{ skills: "Content", subskills: ["Writing"] }],
    type: "open",
    Jobs: [],
  },
  {
    id: "2",
    templateTitle: "UI/UX Review",
    templateDescription: null,
    title: "UI/UX Review",
    slug: "ui-ux-review",
    description:
      '<h2>Về công việc</h2><p>Viết ~2 đoạn văn giải thích công việc. Đoạn đầu tiên nên bao gồm bối cảnh và nền tảng có liên quan về dự án của bạn. Đoạn thứ hai nên giải thích mục tiêu của công việc (ví dụ: các lĩnh vực cần khám phá, các tính năng cần thiết kế lại, bối cảnh xung quanh mục đích của công việc, v.v.). Vui lòng đảm bảo viết công việc ở ngôi thứ 3 (tức là tránh "chúng tôi").   <a href="https://superteam.fun/500-jobs" target="_blank">trang</a> này.</p><p>&nbsp;</p><h2> Phần thưởng</h2><p><strong>🥇Giải nhất:</strong></p><ul><li>Thay thế bằng giải nhất (chúng tôi đề xuất ít nhất 3.000 USDC hoặc số token tương đương của bạn)</li></ul><p>&nbsp;</p><p><strong>🥈 Giải nhì</strong></p><ul><li>Thay thế bằng giải nhì (chúng tôi đề xuất ít nhất 500 USDC hoặc số token tương đương của bạn)</li></ul><p>&nbsp;</p><p><strong>🥉 Giải ba</strong></p><ul><li>Thay thế bằng giải thứ 3 (chúng tôi đề xuất ít nhất $250 USDC hoặc số token tương đương của bạn, nhưng đây là tùy chọn)</li></ul><h2>&nbsp;</h2><h2>Tiêu chí đánh giá</h2><p><em>Người tìm việc sẽ sử dụng các gạch đầu dòng bên dưới để hiểu cách họ sẽ được đánh giá. Vui lòng thêm nhiều tiêu chí hơn hoặc chỉnh sửa các dấu đầu dòng bên dưới nếu cần.</em></p><p>&nbsp;</p><h3><strong>Yêu cầu sâu hơn</strong></h3><ul><li>Bạn có xác định được vấn đề đối với từng màn hình bạn đã kiểm tra không?</li><li>Bạn có giải thích mục tiêu của người dùng đối với các lĩnh vực khác nhau của sản phẩm mà bạn đang đánh giá không?</li><li>Bạn có bao gồm ảnh chụp màn hình của các thiết kế hiện có không?</li><li>Bạn đã tạo ra một thiết kế mới để giải quyết các vấn đề bạn đã xác định chưa?</li><li>Bạn đã thiết kế lại trang web tiếp thị cũng như bất kỳ trang ứng dụng hoặc nội thất nào chưa? Nói cách khác, bạn đã thiết kế lại mọi thứ hiển thị công khai chưa?</li><li>Bạn đã gói bài đánh giá của mình thành một bản trình bày đẹp mắt (ví dụ: Notion, Google Slides, Figma, v.v.) chưa?</li></ul><p>&nbsp;</p><h3><strong>Yêu cầu hồ sơ</strong></h3><ul><li>Chia sẻ nội dung gửi của bạn trên Twitter &amp; tag@<em>dự án của bạn</em></li><li>Hãy xem <a href="https://superteam.substack.com/" target="_blank">những người đạt được công việc trước đây</a> để hiểu được chất lượng mà chúng tôi mong đợi.</li></ul><h2>&nbsp;</h2><h2>Tài liệu</h2><p><em>Vui lòng thêm bất kỳ liên kết nào vào dự án, mạng xã hội của bạn hoặc bất kỳ thứ gì khác sẽ giúp Người tìm việc biết được loại thiết kế mà bạn đang tìm kiếm. Hãy cân nhắc việc đưa Medium/Substack, Twitter, Discord, tài liệu, trang web của bạn và bất kỳ nội dung nào khác có thể hữu ích.</em></p><p>&nbsp;</p><h2>Điều khoản</h2><p><em>Việc tham gia vào công việc này là hoàn toàn tự nguyện. Công việc là một cách để học hỏi và tận dụng các cơ hội để xây dựng trên web3. Đây không phải là công việc toàn thời gian cũng như không phải là sự tham gia dựa trên dự án. Xin lưu ý rằng các công ty sẽ không có thời gian để đưa ra phản hồi riêng lẻ do số lượng bài đăng mà chúng tôi nhận được quá nhiều.</em></p>',
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#F4F0FD",
    emoji: "🖼️",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    created_at: "2023-06-08T10:09:56.129Z",
    updated_at: "2023-06-08T10:09:56.129Z",
    skills: [{ skills: "Design", subskills: ["UI/UX Design"] }],
    type: "open",
    Jobs: [],
  },
  {
    id: "3",
    templateTitle: "Create a dashboard",
    templateDescription: null,
    title: "Create a dashboard",
    slug: "create-a-dashboard",
    description:
      "<h2>Về công việc</h2><p><em>Bên dưới ô này, vui lòng viết 1-2 đoạn văn giải thích dự án của bạn. Điều này có thể bao gồm mô tả sứ mệnh của bạn, minh họa sức hút của bạn, nhà đầu tư của bạn hoặc bất kỳ điều gì khác khiến người tìm việc hào hứng khi làm việc cùng nhau.</em></p><h2>&nbsp;</h2><h2>Số liệu cần bao gồm</h2><p><em>Phần này sẽ giải thích bảng thông tin thành công sẽ bao gồm những gì. Dưới đây là một số thành phần Số liệu cần bao được đề xuất, nhưng vui lòng loại bỏ/giảm bớt nếu cần. </em></p><p>&nbsp;</p><p><strong>Tổng quan</strong></p><ul><li>Xác định khối lượng 24 giờ</li><li>Nhận số lượng giao dịch trong 24 giờ qua</li><li>Khối lượng tích lũy</li><li>Giao dịch tích lũy</li><li>Ví duy nhất tích lũy</li><li>Tổng giá trị đặt cược</li><li>Số nút</li><li>TVL</li><li>Giá trị kho bạc</li></ul><p>&nbsp;</p><p>&nbsp;</p><p><strong>Mã dashboard tổng quan</strong></p><ul><li>Tổng cung</li><li>Nguồn cung lưu thông</li></ul><h2>&nbsp;</h2><h2>Tài liệu</h2><p><em>Vui lòng thêm bất kỳ liên kết nào đến dự án, mạng xã hội hoặc bất kỳ trang tổng quan tham khảo nào có thể giúp người tìm việc hiểu dự án của bạn. Hãy cân nhắc việc đưa Medium/Substack, Twitter, Discord, tài liệu, trang web của bạn và bất kỳ nội dung nào khác có thể hữu ích.</em></p><h2>&nbsp;</h2><h2>Điều khoản</h2><p>Việc tham gia vào công việc này là hoàn toàn tự nguyện. Công việc là một cách để học hỏi và tận dụng các cơ hội để xây dựng trên web3. Đây không phải là công việc toàn thời gian cũng như không phải là sự tham gia dựa trên dự án. Xin lưu ý rằng các công ty sẽ không có thời gian để đưa ra phản hồi riêng lẻ do số lượng bài đăng mà chúng tôi nhận được quá nhiều</p>",
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#F0FCFD",
    emoji: "📈",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    created_at: "2023-06-08T10:09:56.130Z",
    updated_at: "2023-06-08T10:09:56.130Z",
    skills: [{ skills: "Other", subskills: ["Data Analytics"] }],
    type: "open",
    Jobs: [],
  },
  {
    id: "4",
    templateTitle: "Product feedback",
    templateDescription: null,
    title: "Product feedback",
    slug: "product-feedback",
    description:
      '<h2>Về công việc</h2><p><em>Viết ~2 đoạn văn giải thích công việc. Đoạn đầu tiên nên bao gồm bối cảnh và nền tảng có liên quan về dự án của bạn. Đoạn thứ hai nên giải thích mục tiêu của công việc (ví dụ: các lĩnh vực cần khám phá, các tính năng cần thảo luận, bối cảnh xung quanh mục đích của công việc, v.v.). Vui lòng đảm bảo viết công việc ở ngôi thứ 3 (tức là tránh &ldquo;chúng tôi&rdquo;). </em></p><p>&nbsp;</p><p><strong>Nhiệm vụ công việc: </strong>Đăng ký tài khoản với &ldquo;TÊN DỰ ÁN CỦA BẠN&rdquo; và viết báo cáo phản hồi về trải nghiệm của bạn cũng như các đề xuất chung về sản phẩm mà bạn nghĩ đến. Sử dụng Tiêu chí đánh giá và bộ câu hỏi bên dưới để viết báo cáo của bạn.</p><p>&nbsp;</p><h2><strong>Tiêu chí đánh giá</strong></h2><ol><li>Bạn có sử dụng <a href="https://docs.google.com/document/d/1Qaxi5ybbn3J6iaqDM02G-94X0NSV4NJD09UmeU_IU_I/edit?mode=html" target="_blank">Mẫu phản hồi</a> không? (<em>Hãy thoải mái sao chép Mẫu và thêm các câu hỏi tùy chỉnh của riêng bạn. Vui lòng giới hạn số lượng câu hỏi ở mức tối đa 6-10).</em></li><li>Bạn có cung cấp cả phản hồi tích cực và tiêu cực trong báo cáo của mình không?</li><li>Bạn đã thảo luận về các tính năng khác nhau của sản phẩm và trải nghiệm của bạn khi sử dụng nó chưa?</li><li>Bạn có bao gồm ảnh chụp màn hình mô tả các vấn đề hoặc điểm nổi bật để đưa ra bình luận tích cực không?</li><li>Bạn có giới hạn câu trả lời của mình ở mức 70-100 từ cho mỗi câu hỏi không?</li></ol><p>&nbsp;</p><p>&nbsp;</p><h2>Tài liệu</h2><p><em>Thêm bất kỳ liên kết nào đến dự án, mạng xã hội hoặc bất kỳ bài luận tham khảo nào có thể giúp người tìm việc viết một bài đánh giá sản phẩm tuyệt vời. Hãy cân nhắc việc bao gồm Medium/Substack, Twitter, Discord, tài liệu, trang web, quyền truy cập vào sản phẩm của bạn (liên kết truy cập sớm, tệp ứng dụng, v.v.) và bất kỳ điều gì khác có thể hữu ích.</em></p><h2>&nbsp;</h2><h2>Điều khoản</h2><p>Việc tham gia vào công việc này là hoàn toàn tự nguyện. Công việc là một cách để học hỏi và tận dụng các cơ hội để xây dựng trên web3. Đây không phải là công việc toàn thời gian cũng như không phải là sự tham gia dựa trên dự án. Xin lưu ý rằng các công ty sẽ không có thời gian để đưa ra phản hồi riêng lẻ do số lượng bài đăng mà chúng tôi nhận được quá nhiều.</p>',
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#F0F2FD",
    emoji: "📝",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    created_at: "2023-06-08T10:09:56.130Z",
    updated_at: "2023-06-08T10:09:56.130Z",
    skills: [{ skills: "Content", subskills: ["Research"] }],
    type: "open",
    Jobs: [],
  },
  {
    id: "5",
    templateTitle: "Bug Job",
    templateDescription: null,
    title: "Bug Job",
    slug: "bug-job",
    description:
      "<h2>Về chúng tôi</h2><p><em>Ở đây nên có nhiều đoạn văn ngắn (3-5 câu). Đảm bảo truyền đạt rõ ràng sứ mệnh tổng thể là gì, giá trị duy nhất mà dự án của bạn có và bất kỳ bằng chứng nào về sức hút của bạn. Mục tiêu là làm cho công ty của bạn giống như một con tàu tên lửa.</em></p><h2>&nbsp;</h2><h2>Hướng dẫn công việc lỗi</h2><h3>Phạm vi:</h3><ul><li>Những hợp đồng, repos, vv.. nào được xem xét trong phạm vi?</li><li>Những hợp đồng, kho lưu trữ, v.v. nào không nằm trong phạm vi của công việc sửa lỗi này?</li></ul><h3>&nbsp;</h3><h3>Rủi ro nghiêm trọng:</h3><ul><li>Mô tả những gì đủ điều kiện là Rủi ro nghiêm trọng (ví dụ: mất tiền)</li><li>Số tiền thưởng</li></ul><h3>&nbsp;</h3><h3>Rủi ro cấp cao:</h3><ul><li>Mô tả những gì đủ điều kiện là Rủi ro cấp cao (ví dụ: người dùng bị khóa vị trí)</li><li>Số tiền thưởng</li></ul><h3>&nbsp;</h3><h3>Rủi ro cấp trung:</h3><ul><li>Mô tả những gì đủ điều kiện là Rủi ro cấp độ trung bình</li><li>Số tiền thưởng</li></ul><h3>&nbsp;</h3><h3>Rủi ro ở mức độ thấp:</h3><ul><li>Mô tả những gì được coi là rủi ro thấp (ví dụ: các vấn đề về giao diện người dùng, v.v.)</li><li>Số tiền thưởng</li></ul><p>&nbsp;</p>",
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#FBF0FD",
    emoji: "🐞",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    created_at: "2023-06-08T10:09:56.130Z",
    updated_at: "2023-06-08T10:09:56.130Z",
    skills: [{ skills: "Blockchain", subskills: [] }],
    type: "open",
    Jobs: [],
  },
  {
    id: "6",
    templateTitle: "Freelance Designer",
    templateDescription: null,
    title: "Freelance Designer",
    slug: "freelance-designer",
    description:
      "<h2>Chúng ta là ai</h2><p><em>Ở đây nên có nhiều đoạn văn ngắn (3-5 câu). Đảm bảo truyền đạt rõ ràng sứ mệnh tổng thể là gì, cùng với bất kỳ bằng chứng nào về lực kéo của bạn. Mục tiêu là làm cho công ty của bạn giống như một con tàu tên lửa mà các ứng viên sẽ may mắn được làm việc cùng.</em></p><p>&nbsp;</p><h2>Bạn sẽ phải chịu trách nhiệm về...</h2><p><em>Danh sách điểm đầu dòng về phạm vi của vai trò. Họ sẽ sở hữu những gì? Họ sẽ làm việc trên những loại dự án nào? Ở đây, thông tin chi tiết hơn sẽ giúp người nộp đơn hiểu rõ ràng về những gì họ sẽ làm để họ có thể hình dung ra công việc hàng ngày của mình.</em></p><p>&nbsp;</p><p>&nbsp;</p><h2>Bạn là người phù hợp nếu...</h2><p><em>Bao gồm danh sách điểm đầu dòng các yêu cầu cho vai trò (ví dụ: múi giờ, kinh nghiệm, trình độ công nghệ, v.v.). Mục tiêu đạt được ~5 yêu cầu. Nhiều hơn thế sẽ khiến các ứng viên tiềm năng mất hứng thú</em></p><p>&nbsp;</p><p>&nbsp;</p><h2>Bạn là người phù hợp hoàn hảo nếu bạn có</h2><p><em>Đối với &ldquo;tùy chọn&rdquo; hoặc &ldquo;rất vui được có&rdquo; tiêu chí, hãy sử dụng khu vực này. Một lần nữa, hãy cố gắng giới hạn ~5 yêu cầu trở xuống ở đây.</em></p>",
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#F0FDF5",
    emoji: "🥑",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    created_at: "2023-06-08T10:09:56.130Z",
    updated_at: "2023-06-08T10:09:56.130Z",
    skills: [{ skills: "Design", subskills: [] }],
    type: "open",
    Jobs: [],
  },
  {
    id: "7",
    templateTitle: "Write a Twitter thread",
    templateDescription: null,
    title: "Write a Twitter thread",
    slug: "write-a-twitter-thread",
    description:
      "<h2>Về công việc</h2><p><em>Bên dưới ô này, vui lòng viết ~2 đoạn văn giải thích công việc. Đoạn đầu tiên nên bao gồm bối cảnh và nền tảng có liên quan về dự án của bạn. Đoạn thứ hai sẽ giải thích những thông tin nào cần xuất hiện trong chủ đề. </em></p><p>&nbsp;</p><p><strong>Nhiệm vụ của bạn</strong>: Trở thành chuyên gia về TÊN DỰ ÁN CỦA BẠN và tóm tắt những phát hiện của bạn trong một chuỗi Twitter với hơn 8 dòng tweet.</p><h2>&nbsp;</h2><h2>Tiêu chí đánh giá</h2><p><em>Người tìm việc sẽ sử dụng các gạch đầu dòng bên dưới để hiểu cách họ sẽ được đánh giá. Vui lòng thêm nhiều tiêu chí hơn (ví dụ: nếu bạn muốn họ thảo luận về một tính năng cụ thể trong dự án của bạn) hoặc chỉnh sửa các dấu đầu dòng bên dưới nếu cần.</em></p><p>&nbsp;</p><h3>Yêu cầu sâu hơn</h3><ul><li>Bạn đã khám phá nền tảng của dự án?</li><li>Chủ đề của bạn có nói về các tính năng chính của dự án không?</li><li>Chủ đề của bạn có phải là nguồn tài nguyên duy nhất để mọi người bắt kịp dự án này không?</li><li>Bạn đã tìm hiểu mọi thứ cần biết về dự án chưa?</li><li>Bạn đã thử tham gia cuộc thi và giải thích những ưu/nhược điểm tương đối của dự án này chưa?</li></ul><p>&nbsp;</p><h3><strong>Phong cách viết</strong></h3><ul><li>Bài viết của bạn có dễ đọc và thú vị không?</li><li>Bạn có tránh dùng những biệt ngữ quá phức tạp không?</li><li>Bạn có giải thích các khái niệm theo cách mà một người mới làm quen với tiền điện tử có thể hiểu được không?</li></ul><p>&nbsp;</p><h3><strong>Yêu cầu nộp đơn</strong></h3><ul><li>Bạn có gắn thẻ công ty trong chuỗi Tweet của mình cùng với công ty không?</li></ul><h2>&nbsp;</h2><h2>Tài liệu</h2><p><em>Vui lòng thêm bất kỳ liên kết nào đến dự án, mạng xã hội hoặc bất kỳ bài luận tham khảo nào của bạn có thể giúp người tìm việc viết một chủ đề hay. Hãy cân nhắc việc đưa Medium/Substack, Twitter, Discord, tài liệu, trang web của bạn và bất kỳ nội dung nào khác có thể hữu ích.</em></p><h2>&nbsp;</h2><h2>Điều khoản</h2><p>Việc tham gia vào công việc này là hoàn toàn tự nguyện. Công việc là một cách để học hỏi và tận dụng các cơ hội để xây dựng trên web3. Đây không phải là công việc toàn thời gian cũng như không phải là sự tham gia dựa trên dự án. Xin lưu ý rằng các công ty sẽ không có thời gian cho phản hồi cá nhân do số lượng bài dự thi họ nhận được quá nhiều.</p>",
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#FDF0F0",
    emoji: "🧵",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    created_at: "2023-06-08T10:09:56.129Z",
    updated_at: "2023-06-08T10:09:56.129Z",
    skills: [{ skills: "Content", subskills: ["Writing"] }],
    type: "open",
    Jobs: [],
  },
];
